"""Pydantic-схемы API дня 18: единое место моделей, разложенное по доменам.

Схемы перенесены из монолитного ``models.py`` без изменений и реэкспортируются
отсюда, поэтому код дня (и тесты) импортирует их из ``backend.schemas``.
ORM-таблицы — отдельный пакет ``backend/models/``.

- ``agent.py``   — агент, генерация, метрики использования токенов;
- ``context.py`` — сжатие истории, стратегии, ветки, факты;
- ``invariant.py`` — инварианты проекта дня 14 и результат проверки текста;
- ``memory.py``  — три слоя памяти агента;
- ``mcp.py``     — MCP дня 17: статус подключения, инструменты (name,
  description, input_schema, output_schema), их вызов и каталог серверов;
- ``scheduler.py`` — планировщик дня 18: инструменты, задачи, их запуски,
  напоминания, накопленные записи, сводки, уведомления и отчёт ``schedule``;
- ``pipeline.py`` — пайплайн дня 19: запуск, его шаги, история и отчёт о прогоне;
- ``profile.py`` — профиль пользователя и его вклад в промпт;
- ``task.py``    — состояние задачи: этап, шаг, контролируемые переходы (день 15),
  флаги-согласования и журнал попыток.
"""

from .agent import (
    AgentConfig,
    AgentPatch,
    AgentSummary,
    AgentInfo,
    GenerateRequest,
    MessageOut,
    TokenMetrics,
    UsageOut,
    UsageSummary,
    GenerateResponse,
)

from .context import (
    CompressionInfo,
    ContextInfo,
    SummaryOut,
    SummaryInfo,
    SummarizeRequest,
    CompareRequest,
    CompareSide,
    CompareResult,
    StrategySetRequest,
    StrategiesOut,
    BranchCreateRequest,
    BranchOut,
    BranchListOut,
    FactOut,
    FactsOut,
)

from .invariant import (
    InvariantCheckIn,
    InvariantCheckOut,
    InvariantIn,
    InvariantOut,
    InvariantUpdateIn,
    InvariantViolationOut,
)

from .memory import (
    MemoryLayerInfo,
    MemoryInfo,
    ShortTermMessageIn,
    ShortTermMessageOut,
    ShortTermOut,
    ShortTermClearOut,
    WorkingEntryIn,
    WorkingEntryOut,
    WorkingMemoryOut,
    LongTermEntryIn,
    LongTermEntryOut,
    LongTermMemoryOut,
    LongTermDeleteOut,
    SessionOut,
    TaskSetRequest,
    TaskOut,
)

from .mcp import (
    MCPCallIn,
    MCPCallReportOut,
    MCPCallResponse,
    MCPConnectIn,
    MCPServerSchema,
    MCPServersResponse,
    MCPStatusResponse,
    MCPToolSchema,
    MCPToolsResponse,
)

from .pipeline import (
    PipelineReportOut,
    PipelineRunIn,
    PipelineRunOut,
    PipelineRunReportOut,
    PipelineRunsResponse,
    PipelineStartOut,
    PipelineStepOut,
    PipelineStepsResponse,
)

from .profile import (
    UserPreferences,
    UserConstraints,
    UserProfileIn,
    UserProfileOut,
    UserProfileDeleteOut,
    ProfileElementOut,
    AppliedProfileOut,
)

from .scheduler import (
    CollectedRecordOut,
    CollectedResponse,
    NotificationOut,
    NotificationsResponse,
    PeriodicSummaryOut,
    ReminderOut,
    RemindersResponse,
    ScheduleReportOut,
    ScheduledTaskOut,
    SchedulerRunOut,
    SchedulerRunsResponse,
    SchedulerStatusOut,
    SchedulerTaskCreateOut,
    SchedulerTaskIn,
    SchedulerTasksResponse,
    SchedulerToolArgument,
    SchedulerToolSchema,
    SchedulerToolsResponse,
    SummariesResponse,
)

from .task import (
    TaskAllowedNextOut,
    TaskBlockedOut,
    TaskCreateIn,
    TaskFlagsIn,
    TaskHistoryOut,
    TaskRollbackIn,
    TaskStateOut,
    TaskTransitionIn,
    TaskTransitionOut,
)

__all__ = [
    "AgentConfig",
    "AgentInfo",
    "AgentPatch",
    "AgentSummary",
    "AppliedProfileOut",
    "BranchCreateRequest",
    "BranchListOut",
    "BranchOut",
    "CollectedRecordOut",
    "CollectedResponse",
    "CompareRequest",
    "CompareResult",
    "CompareSide",
    "CompressionInfo",
    "ContextInfo",
    "FactOut",
    "FactsOut",
    "GenerateRequest",
    "GenerateResponse",
    "InvariantCheckIn",
    "InvariantCheckOut",
    "InvariantIn",
    "InvariantOut",
    "InvariantUpdateIn",
    "InvariantViolationOut",
    "LongTermDeleteOut",
    "LongTermEntryIn",
    "LongTermEntryOut",
    "LongTermMemoryOut",
    "MCPConnectIn",
    "MCPCallIn",
    "MCPCallReportOut",
    "MCPCallResponse",
    "MCPServerSchema",
    "MCPServersResponse",
    "MCPStatusResponse",
    "MCPToolSchema",
    "MCPToolsResponse",
    "MemoryInfo",
    "MemoryLayerInfo",
    "MessageOut",
    "NotificationOut",
    "NotificationsResponse",
    "PeriodicSummaryOut",
    "ProfileElementOut",
    "ReminderOut",
    "RemindersResponse",
    "ScheduleReportOut",
    "ScheduledTaskOut",
    "SchedulerRunOut",
    "SchedulerRunsResponse",
    "SchedulerStatusOut",
    "SchedulerTaskCreateOut",
    "SchedulerTaskIn",
    "SchedulerTasksResponse",
    "SchedulerToolArgument",
    "SchedulerToolSchema",
    "SchedulerToolsResponse",
    "SessionOut",
    "ShortTermClearOut",
    "ShortTermMessageIn",
    "ShortTermMessageOut",
    "ShortTermOut",
    "StrategiesOut",
    "StrategySetRequest",
    "SummarizeRequest",
    "SummariesResponse",
    "SummaryInfo",
    "SummaryOut",
    "TaskAllowedNextOut",
    "TaskBlockedOut",
    "TaskCreateIn",
    "TaskFlagsIn",
    "TaskHistoryOut",
    "TaskOut",
    "TaskRollbackIn",
    "TaskSetRequest",
    "TaskStateOut",
    "TaskTransitionIn",
    "TaskTransitionOut",
    "TokenMetrics",
    "UsageOut",
    "UsageSummary",
    "UserConstraints",
    "UserPreferences",
    "UserProfileDeleteOut",
    "UserProfileIn",
    "UserProfileOut",
    "WorkingEntryIn",
    "WorkingEntryOut",
    "WorkingMemoryOut",
]
