"""Pydantic-схемы API дня 18: единое место моделей, разложенное по доменам.

Схемы перенесены из монолитного ``models.py`` без изменений и реэкспортируются
отсюда, поэтому код дня (и тесты) импортирует их из ``backend.schemas``.
ORM-таблицы — отдельный пакет ``backend/models/``.

- ``agent.py``   — агент, генерация, метрики использования токенов;
- ``context.py`` — сжатие истории, стратегии, ветки, факты;
- ``invariant.py`` — инварианты проекта дня 14 и результат проверки текста;
- ``memory.py``  — три слоя памяти агента;
- ``mcp.py``     — MCP дня 17: статус подключения, инструменты и их вызов;
- ``mcp_servers.py`` — флот серверов дня 20: состав, состояние, инструменты и кэш;
- ``scheduler.py`` — планировщик дня 18: инструменты, задачи, запуски, сводки, отчёт ``schedule``;
- ``pipeline.py`` — пайплайн дня 19: запуск, его шаги, история и отчёт о прогоне;
- ``indexing.py`` — индексация дня 21: запуск прогона, статистика, поиск, очистка индекса;
- ``llm.py`` — расходы на LLM: журнал, кэш, непиковые часы и таблица «тип задачи → модель»;
- ``profile.py`` — профиль пользователя и его вклад в промпт;
- ``rag.py`` — RAG: запрос по корпусу, сравнение ответов и режимов, состояние корпуса;
- ``rag_compare.py`` — сравнение провайдеров: строки «вопрос → локальный/облачный ответ → вердикт» и сводка;
- ``mini_chat.py`` — мини-чат дня 25: сессия, ответ по корпусу, память задачи, история;
- ``task.py``    — состояние задачи: этап, шаг, переходы дня 15, флаги и журнал попыток.
"""

from .agent import (
    AgentConfig,
    AgentPatch,
    AgentSummary,
    AgentInfo,
    GenerateRequest,
    MessageOut,
    TokenMetrics,
    UsageOut,
    UsageSummary,
    GenerateResponse,
)

from .context import (
    CompressionInfo,
    ContextInfo,
    SummaryOut,
    SummaryInfo,
    SummarizeRequest,
    CompareRequest,
    CompareSide,
    CompareResult,
    StrategySetRequest,
    StrategiesOut,
    BranchCreateRequest,
    BranchOut,
    BranchListOut,
    FactOut,
    FactsOut,
)

from .invariant import (
    InvariantCheckIn,
    InvariantCheckOut,
    InvariantIn,
    InvariantOut,
    InvariantUpdateIn,
    InvariantViolationOut,
)

from .indexing import (
    IndexChunkListOut,
    IndexChunkOut,
    IndexClearIn,
    IndexClearOut,
    IndexDemoIn,
    IndexingReportOut,
    IndexRunIn,
    IndexRunOut,
    IndexRunReportOut,
    IndexRunsResponse,
    IndexSearchOut,
    IndexStartOut,
    IndexStatsOut,
    IndexStatsResponse,
    IndexStatusOut,
)

from .llm import (
    LLMEstimateIn,
    LLMModelsOut,
    LLMPromptStatsOut,
    LLMCompressorStatsOut,
    LLMSavingsOut,
    LLMStatsOut,
    LLMStatusOut,
    LLMUsageOut,
    LLMUsageResponse,
    LocalDemoOut,
    LocalDemoRowOut,
)

from .memory import (
    MemoryLayerInfo,
    MemoryInfo,
    ShortTermMessageIn,
    ShortTermMessageOut,
    ShortTermOut,
    ShortTermClearOut,
    WorkingEntryIn,
    WorkingEntryOut,
    WorkingMemoryOut,
    LongTermEntryIn,
    LongTermEntryOut,
    LongTermMemoryOut,
    LongTermDeleteOut,
    SessionOut,
    TaskSetRequest,
    TaskOut,
)

from .mini_chat import (
    MiniChatAnswerOut,
    MiniChatCloseOut,
    MiniChatHistoryMessageOut,
    MiniChatHistoryOut,
    MiniChatMessageIn,
    MiniChatSessionIn,
    MiniChatSessionOut,
    MiniChatTaskMemoryOut,
)

from .mcp_servers import (
    MCPRefreshResponse,
    MCPServerInfo,
    MCPServerToolsResponse,
    MCPServersResponse,
    MCPToolInfoPayload,
)
from .mcp import (
    MCPCallIn,
    MCPCallReportOut,
    MCPCallResponse,
    MCPConnectIn,
    MCPStatusResponse,
    MCPToolSchema,
    MCPToolsResponse,
)

from .orchestration import (
    OrchestrationDemoIn,
    OrchestrationReportOut,
    OrchestrationRunIn,
    OrchestrationRunOut,
    OrchestrationRunReportOut,
    OrchestrationRunsResponse,
    OrchestrationStartOut,
    OrchestrationStepOut,
    OrchestrationStepsResponse,
)
from .pipeline import (
    PipelineReportOut,
    PipelineRunIn,
    PipelineRunOut,
    PipelineRunReportOut,
    PipelineRunsResponse,
    PipelineStartOut,
    PipelineStepOut,
    PipelineStepsResponse,
)

from .profile import (
    UserPreferences,
    UserConstraints,
    UserProfileIn,
    UserProfileOut,
    UserProfileDeleteOut,
    ProfileElementOut,
    AppliedProfileOut,
)

from .rag import (
    RagCompareIn,
    RagCompareOut,
    RagConfigOut,
    RagCorpusOut,
    RagDemoIn,
    RagDemoOut,
    RagDemoQuestionOut,
    RagDemoQuestionsOut,
    RagDemoRowOut,
    RagDemoSummaryOut,
    RagIndexOut,
    RagModeOut,
    RagModesIn,
    RagModesOut,
    RagQueryIn,
    RagQueryOut,
    RagQuoteOut,
    RagSourceOut,
    RagTokensOut,
)

from .rag_compare import (
    RagCompareProvidersIn,
    RagCompareProvidersOut,
    RagProviderRowOut,
    RagProviderSummaryOut,
)

from .scheduler import (
    CollectedRecordOut,
    CollectedResponse,
    NotificationOut,
    NotificationsResponse,
    PeriodicSummaryOut,
    ReminderOut,
    RemindersResponse,
    ScheduleReportOut,
    ScheduledTaskOut,
    SchedulerRunOut,
    SchedulerRunsResponse,
    SchedulerStatusOut,
    SchedulerTaskCreateOut,
    SchedulerTaskIn,
    SchedulerTasksResponse,
    SchedulerToolArgument,
    SchedulerToolSchema,
    SchedulerToolsResponse,
    SummariesResponse,
)

from .task import (
    TaskAllowedNextOut,
    TaskBlockedOut,
    TaskCreateIn,
    TaskFlagsIn,
    TaskHistoryOut,
    TaskRollbackIn,
    TaskStateOut,
    TaskTransitionIn,
    TaskTransitionOut,
)

__all__ = [
    "AgentConfig",
    "AgentInfo",
    "AgentPatch",
    "AgentSummary",
    "AppliedProfileOut",
    "BranchCreateRequest",
    "BranchListOut",
    "BranchOut",
    "CollectedRecordOut",
    "CollectedResponse",
    "CompareRequest",
    "CompareResult",
    "CompareSide",
    "CompressionInfo",
    "ContextInfo",
    "FactOut",
    "FactsOut",
    "GenerateRequest",
    "GenerateResponse",
    "IndexChunkListOut",
    "IndexChunkOut",
    "IndexClearIn",
    "IndexClearOut",
    "IndexDemoIn",
    "IndexingReportOut",
    "IndexRunIn",
    "IndexRunOut",
    "IndexRunReportOut",
    "IndexRunsResponse",
    "IndexSearchOut",
    "IndexStartOut",
    "IndexStatsOut",
    "IndexStatsResponse",
    "IndexStatusOut",
    "InvariantCheckIn",
    "InvariantCheckOut",
    "InvariantIn",
    "InvariantOut",
    "InvariantUpdateIn",
    "InvariantViolationOut",
    "LongTermDeleteOut",
    "LongTermEntryIn",
    "LongTermEntryOut",
    "LLMCompressorStatsOut",
    "LLMEstimateIn",
    "LLMModelsOut",
    "LLMPromptStatsOut",
    "LLMSavingsOut",
    "LLMStatsOut",
    "LLMStatusOut",
    "LLMUsageOut",
    "LLMUsageResponse",
    "LocalDemoOut",
    "LocalDemoRowOut",
    "LongTermMemoryOut",
    "MCPCallIn",
    "MCPCallReportOut",
    "MCPCallResponse",
    "MCPConnectIn",
    "MCPRefreshResponse",
    "MCPServerInfo",
    "MCPServerToolsResponse",
    "MCPServersResponse",
    "MCPStatusResponse",
    "MCPToolInfoPayload",
    "MCPToolSchema",
    "MCPToolsResponse",
    "MemoryInfo",
    "MemoryLayerInfo",
    "MessageOut",
    "MiniChatAnswerOut",
    "MiniChatCloseOut",
    "MiniChatHistoryMessageOut",
    "MiniChatHistoryOut",
    "MiniChatMessageIn",
    "MiniChatSessionIn",
    "MiniChatSessionOut",
    "MiniChatTaskMemoryOut",
    "NotificationOut",
    "NotificationsResponse",
    "OrchestrationDemoIn",
    "OrchestrationReportOut",
    "OrchestrationRunIn",
    "OrchestrationRunOut",
    "OrchestrationRunReportOut",
    "OrchestrationRunsResponse",
    "OrchestrationStartOut",
    "OrchestrationStepOut",
    "OrchestrationStepsResponse",
    "PeriodicSummaryOut",
    "ProfileElementOut",
    "RagCompareIn",
    "RagCompareOut",
    "RagCompareProvidersIn",
    "RagCompareProvidersOut",
    "RagConfigOut",
    "RagCorpusOut",
    "RagDemoIn",
    "RagDemoOut",
    "RagDemoQuestionOut",
    "RagDemoQuestionsOut",
    "RagDemoRowOut",
    "RagDemoSummaryOut",
    "RagIndexOut",
    "RagModeOut",
    "RagModesIn",
    "RagModesOut",
    "RagProviderRowOut",
    "RagProviderSummaryOut",
    "RagQueryIn",
    "RagQueryOut",
    "RagQuoteOut",
    "RagSourceOut",
    "RagTokensOut",
    "ReminderOut",
    "RemindersResponse",
    "ScheduleReportOut",
    "ScheduledTaskOut",
    "SchedulerRunOut",
    "SchedulerRunsResponse",
    "SchedulerStatusOut",
    "SchedulerTaskCreateOut",
    "SchedulerTaskIn",
    "SchedulerTasksResponse",
    "SchedulerToolArgument",
    "SchedulerToolSchema",
    "SchedulerToolsResponse",
    "SessionOut",
    "ShortTermClearOut",
    "ShortTermMessageIn",
    "ShortTermMessageOut",
    "ShortTermOut",
    "StrategiesOut",
    "StrategySetRequest",
    "SummarizeRequest",
    "SummariesResponse",
    "SummaryInfo",
    "SummaryOut",
    "TaskAllowedNextOut",
    "TaskBlockedOut",
    "TaskCreateIn",
    "TaskFlagsIn",
    "TaskHistoryOut",
    "TaskOut",
    "TaskRollbackIn",
    "TaskSetRequest",
    "TaskStateOut",
    "TaskTransitionIn",
    "TaskTransitionOut",
    "TokenMetrics",
    "UsageOut",
    "UsageSummary",
    "UserConstraints",
    "UserPreferences",
    "UserProfileDeleteOut",
    "UserProfileIn",
    "UserProfileOut",
    "WorkingEntryIn",
    "WorkingEntryOut",
    "WorkingMemoryOut",
]
